# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: "3.8"

services:
  kafka:
    image: docker.io/bitnami/kafka:3.6
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    networks:
      - cluster
    healthcheck:
      test: /opt/bitnami/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server localhost:9092 || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Configs
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

  postgres:
    image: postgres:16.1-bullseye
    container_name: postgres
    hostname: postgres
    networks:
      - cluster
    environment:
      POSTGRES_DB: precipitation_forecast
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - "kafka_data:/var/lib/postgresql"

  forecast_simulator:
    build:
      context: ./forecast_simulator
    container_name: forecast_simulator
    volumes:
      - ./forecast_simulator:/opt/app
    networks:
      - cluster
    depends_on:
      kafka:
        condition: service_healthy

  processor:
    build:
      context: ./processor
    user: root
    container_name: processor
    networks:
      - cluster
    ports:
      - "4040:4040"
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_started

  prometheus:
    image: prom/prometheus:v2.45.3
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - cluster
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    networks:
      - cluster
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

volumes:
  kafka_data:
    name: kafka_data
    driver: local
  postgres_data:
    name: postgres_data
    driver: local
  prom_data:

networks:
  cluster:
    name: cluster
    driver: bridge
