{
 "title": "Spark",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Active Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active task count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    { "expr": "metrics_executor_activeTasks", "legendFormat": "Active task count" },
    {
     "expr": "avg_over_time(metrics_executor_activeTasks[1h])",
     "legendFormat": "Average cask count"
    }
   ]
  },
  {
   "title": "Completed tasks last minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(metrics_executor_completedTasks_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed tasks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_executor_failedTasks_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active task count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "metrics_executor_activeTasks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mean task count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "metrics_executor_activeTasks", "legendFormat": "__auto" }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory used in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "metrics_executor_memoryUsed_bytes",
     "legendFormat": "Memory used in bytes"
    },
    {
     "expr": "avg_over_time(metrics_executor_memoryUsed_bytes[10m])",
     "legendFormat": "Average memory used in bytes"
    }
   ]
  },
  {
   "title": "Shuffle amount change I/O in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "delta(metrics_executor_totalShuffleRead_bytes_total[60m])",
     "legendFormat": "Shuffle read"
    },
    {
     "expr": "delta(metrics_executor_totalShuffleWrite_bytes_total[60m])",
     "legendFormat": "Shuffle write"
    }
   ]
  }
 ]
}